apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:   # ✅ Corrected indentation and uppercase 'L'
      app: nginx-app
  template:        # ✅ Moved `spec` under `template`
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: sathwickgowda8642/my-nginx-app:latest
          ports:
            - containerPort: 80

  


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
# #       containers:
# #       - name: nginx
# #         image: your-docker-hub-username/my-nginx-app:latest
# #         ports:
# #         - containerPort: 80


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-nginx-deployment
#   labels:
#     app: my-nginx
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: my-nginx
#   template:
#     metadata:
#       labels:
#         app: my-nginx
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:latest
#           ports:
#             - containerPort: 80
