# # name: Deploy NGINX

# # on: 
# #     push:
# #         branches:
# #             - main

# # jobs:
# #     deploy:
# #         runs-on: ubuntu-latest

# #         steps:
# #             - name: Checkout Code
# #               uses: actions/checkout@v4

# #             - name: Set up Docker Build
# #               run: docker build -t my-nginx-app ./nginx

# #             - name: Run Container
# #               run: docker run -d -p 7070:80 my-nginx-app

# name: Deploy to Docker Hub

# on:
#   push:
#     branches:
#       - main  # Runs only when code is pushed to main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Log in to Docker Hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#       - name: Build and tag Docker Image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest ./nginx
#           docker tag ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest ${{secrets.DOCKER_USERNAME}}/my-nginx-app:latest

#       - name: Push to Docker Hub
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest



name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest ./nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml 
          kubectl apply -f service.yaml 
